blank_issues_enabled: false

issue_templates:
  - name: ğŸ‘¾ Reportar un Bug
    description: InformÃ¡ un error o comportamiento inesperado del sistema.
    file: bug_report.md

  - name: ğŸš€ Solicitud de funcionalidad
    description: ProponÃ© una nueva funcionalidad o mejora para el proyecto.
    file: feature_request.md

  - name: ğŸ§‘â€ğŸ’¼ User Story
    description: DefinÃ­ una funcionalidad desde el punto de vista del usuario final.
    file: user_story.md

  - name: ğŸ“˜ Epic
    description: DocumentÃ¡ una iniciativa grande que agrupa varias historias o tareas.
    file: epic.md